### ISSUE TITLE
Make question-option text clickable

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/betterquiz#1]
To answer a question, a user must click/tap the radio button exactly. The question-option text should also be tap/clickable. To do this, a slight change to the HTML:
- use `<label class="option-text">` not `<div class="option-text">`
- assign an ID to `<input>`
- add `for="ID"` to `<label>`.

E.g.

``` html
<input type="radio" name="o6" value="21" id="o6" class="option-radio">
<label class="option-text" for="o6">Question text</label>
```

**Comment by arthurattwell** [comment]
@craigmj Is this a small code tweak (few minutes work) or a structural change that will take time? If a tweak, we should make a plan to do it now. If a change that will need longer, I could call it an enhancement for later. But I reckon it will make a huge difference to the user experience.

**Comment by craigmj** [comment]
Corrected.
