### ISSUE TITLE
Convert markdown emphasis and strong to HTML

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/betterquiz#12]
Markdown uses asterisks to enclose spans that convert to HTML emphasis or strong.

`*emphasis*` = `<em>emphasis</em>`

`**strong**` = `<strong>strong</strong>`

BQF should process this markdown the same way.

(For now, we'll do without emphasis or strong in our quizzes.)

**Comment by craigmj** [comment]
Done. Any markdown in a question or option is assumed to by wrapped in a <p> once converted to html, and this is necessarily stripped. Otherwise, any required md should work without question or option text.
