### ISSUE TITLE
Forgot-password process gives potentially unauthorised user access

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/betterquiz#13]
if I have someone's email address, I can get into their account because, when I follow the forgot password process, I am given the new password in plain text on screen. So the new password should not be provided on screen, only in the email sent.

Process to reproduce:
1. Click Forgot password
2. Enter any registered email address
3. Click Forgot password
4. Returns: "We've emailed you a new password (lecqtc4k)."

![20150801_forgot-password-gives-password](https://cloud.githubusercontent.com/assets/1053331/9023165/a59d5828-3890-11e5-870d-8f49f05a406b.jpg)

**Comment by craigmj** [comment]
Fixed.
