### ISSUE TITLE
An answer option starting with `0` causes errors

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/betterquiz#15]
When an answer option in a question starts with `0` we get unexpected behaviour:
- when the `0` is on its own, betterquiz won't import the quiz at all (`Expecting a question but got option at`)
- when the `0` starts the line, the importer puts an empty line after the `0`, which breaks the quiz.

To reproduce, save this as a `.bqf` file, upload to betterquiz, and view the BQF and/or try the quiz:

```
title: Testing error when answer option is 0

What is the normal total serum bilirubin concentration (TSB) in cord blood?
-   0 this zero creates a line break. On its own as an option, it throws an error
+   Less than 35 µmol/l
-   35–55 µmol/l
-   More than 55 µmol/l

What is the normal total serum bilirubin concentration (TSB) in cord blood?
-   0 µmol/l
+   Less than 35 µmol/l
-   35–55 µmol/l
-   More than 55 µmol/l
```

**Comment by arthurattwell** [comment]
Further testing shows that this:

```
What is a safe concentration of inspired oxygen?
-   0.40 (i.e. 40%)
-   0.25 (i.e. 25%)
-   0.10 (i.e. 10%)
+   Any FiO₂ that gives a normal partial pressure or normal saturation of oxygen in the blood
```

Becomes this in BQF after uploading:

```
What is a safe concentration of inspired oxygen?
- 0
- 40 (i.e. 40%)
- 0
- 25 (i.e. 25%)
- 0
- 10 (i.e. 10%)
+ Any FiO₂ that gives a normal partial pressure or normal saturation of oxygen in the blood
```

Probably related: we also get an error when a question starts with `100%`:

```
100% oxygen may damage the infant and therefore:
- Should never be given to any infant
- Should not be given for more than 24 hours
+ Should only be given if a lower concentration of oxygen fails to correct central cyanosis
- Should never be given to a preterm infant
```

becomes

```
10

% oxygen may damage the infant and therefore:
- Should never be given to any infant
- Should not be given for more than 24 hours
+ Should only be given if a lower concentration of oxygen fails to correct central cyanosis
- Should never be given to a preterm infant
```

**Comment by arthurattwell** [comment]
A workaround is to paste a hairspace (here's one: ` `) at the start of the option or question in the source BQF file.

**Comment by craigmj** [comment]
Fixed. Also zeros appearing in meta data would have been causing trouble - I've fixed for those as well. The cause was PHP's happy conversion of a "0" string to a FALSE value in comparisons! Aaargh!

Tests for this situations have been added to the test suite to ensure that are checked for automatically.

PS: Thank you for a really awesome bug report :)

**Comment by arthurattwell** [comment]
Fantastic, thanks, Craig! :)
