### ISSUE TITLE
Admin area not showing user list

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/betterquiz#16]
When I navigate to [http://quiz.bettercare.co.za/admin/user-list.php](http://quiz.bettercare.co.za/admin/user-list.php) no users are listed, and I cannot find users from search.

**Comment by craigmj** [comment]
Fixed :) Sorry, bug caused by the merging of users code.

Hope all is going well,
C

**Comment by arthurattwell** [comment]
Super, thanks, Craig! That was fast. Much appreciated.

All good here!
