### ISSUE TITLE
Admin pagination links not clickable in Safari on OSX

### ISSUE THREAD

**Issue by arthurattwell** [electricbookworks/betterquiz#17]
Note: This is **not** an important bug because it only affects admin users in specific browsers. Just recording it here so we don't forget about it entirely. It does not need fixing at this stage.

In admin, the pagination links (at the bottom of the page) on:

[http://quiz.bettercare.co.za/admin/quiz-list.php](http://quiz.bettercare.co.za/admin/quiz-list.php)

and

[http://quiz.bettercare.co.za/admin/user-list.php](http://quiz.bettercare.co.za/admin/user-list.php)

are not clickable.

**Comment by craigmj** [comment]
Same bug appeared in Firefox. Both are now fixed, and tested on Safari.
